dist: xenial
language: python
python:
- '3.6'
- '3.7'
env:
- AWS_DEFAULT_REGION=us-east-1
install:
- pip install -r requirements-dev.txt
- pip install google-compute-engine
script:
- bash test.sh
deploy:
  provider: pypi
  username: journera
  password:
    secure: i/YjDqmba77S//KhgbYzX3unb41fVhTYAwYoBk6tw946Px1/ZPdncAdCLROhliI7rwvza7uLq88symHq3HJxeTU6OrBj8Bgsp2nlaLgNyf7iy7nsAjK1CM4qz2Ml/nLbKAwon/9Nj2mnUu1Yo8RrE461GS65+pvMHUkPS5mVkbinNMHKG81QB37NyVXwZZVuLg11iqWAH7tFisVUsVypdbfCTJ6lJTlxfzh9BpzHGRKWWgDeCQEz9Tu+eKvWbR26uo0M/rYVyzxl2stG/CQK0UBTjKSujArqgoNZh4z332dE3hE9GXHOkM4X2ARNSFpcf8m5D+YriI8cqV+28JlPhAjhN2cRyYZf+fJN+NOAB850XLhXdiocyF9wjW9nMsUJXjc7hyZCaudMEBkAxLJvU0z8n1jwDQZTcT/DXFtsAARNOwat+rsXS8qd+ToQlXVO9iBFt0pTcQI9b7SvAQxfUnB79QTYrvVF6UH4TnvJNszbVUtRIsEsYIfcPHtbSiLUJiRUYJ0606xDkRbSzthiFPNX6jwqzqca5umhLO+lgt2elOrRuf8bwy64s8WTXwXHtPvw4eFWjTx1BAQkxCMaEKXwC1WqZ7VuQs14RAUIc3GGTnaTqyA0ekHiwx1GXGM61K0VdHlGdIgaLU2gQAwRrajNwQGzOebsB70r+3N1XI0=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
