dist: xenial
language: python
python:
- '3.6'
- '3.7'
env:
- AWS_DEFAULT_REGION=us-east-1
install:
- pip install -r requirements-dev.txt
- pip install google-compute-engine
script:
- bash test.sh
deploy:
  provider: pypi
  username: journera
  password:
    secure: Pc5gcuzmAdPFAG0bhSQF7/P5dweSHkknci64JP7H/PNHqh9uNc+8RLO4tzGPFdXm31tVeMJDFVVYQkjlIwMIHO0H+wYG1c9EK16WeLLJeb2iBdVsEH8X0cZDmpj67nbFmx4pZ5vB+SA4KRysGtE/cki8nCVg8NBsy5SEixS3M5oIK6o7E0DfPR4EPBG+fLQcciAYLjO6aoDxKo5I4oFzZsiAnXuSzZz/3RF+kqN3mn0u8QmwxZq6c2IXQ6UtXTrTRw6kr1iSrRdMbmgmqgg4AEznYvduFfi8YF6m3pwC3dFXQG+I8E6kIkiVhL4xDvIKJhgtSgLzsoPcqh4SO4Zn/ZfdhBNmo2hI2RlUqeacYIQHXDOhSzyIwOJs+oey6jn+lxko1uBVn6uNdcH936xEoOenLvsFv6wsM/mCzRfEO0J+iniB0nRwxAlQDMt9T4z7KzMidFBFchzc+eWcphqLcpyD8kz/51Div9eI4ctmFOMzySVfIDnVrrQBh/T5RTsr602PnrvCvNsdDhfFHO4nksCXWn89oOwRrm274iDZHhn1ruYXtUmyWRF9MKPkS2okzjPCj2T75nX1uLK7ZnTrs7udLPifOWEtN7anHPdJKu+A4Zc8CB+5CV840hklq+4u6jtSCoR9uMqlVtyK5YEHjWnwcrQiw/893D+GCmBmVao=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
